aws_region          = "us-east-1"
project_id          = "cmtr-pf5k68pq"
vpc_name            = "cmtr-pf5k68pq-vpc"
public_subnet_name  = "cmtr-pf5k68pq-public-subnet-1"
security_group_name = "cmtr-pf5k68pq-sg"
